name: environment-vars-test

on:
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  create-env-files:    
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: test-secret-vars-text-quotes
      run: echo SOME_ENV_VAR_WITH_QUOTES=${{ vars.SOME_ENV_VAR_WITH_QUOTES }} >> .env;
        my_var=${{ vars.SOME_ENV_VAR_WITH_QUOTES }};
        cat <<< "SOME_ENV_VAR_WITH_QUOTES=$my_var" >> .env;
        echo SOME_SECRET_KEY=${{ secrets.SOME_SECRET_KEY }} >> .env; 
        cat .env;
